@startuml

left to right direction


class 予約年月日
enum 予約開始_時
enum 予約終了_時
enum 予約_分

class 予約期間{
    - 開始
    - 終了
}

class 予約開始日時
class 予約終了日時

note left of 予約期間
未）開始<終了
未）開始と終了が同じ日付であること
10:00-19:00というルールは、自ずと出来ている
最大9時間
end note

note left of 予約_分
15分単位であること
end note


予約開始日時 *-- 予約年月日
予約開始日時 *-- 予約開始_時
予約開始日時 *-- 予約_分
予約終了日時 *-- 予約年月日
予約終了日時 *-- 予約終了_時
予約終了日時 *-- 予約_分

予約期間 *-- 予約開始日時
予約期間 *-- 予約終了日時

note left of 予約期間
10:00 - 11:00 の予約は、 [10:00,11:00)となる。
10:00を含め、11:00は含まない。
表現としては、終了時刻は11:00として扱うけど、
イメージとしては、10:59:59.999999999999999999...
end note

note left of 予約開始日時
10:00-18:45
19:00という時間を、そもそも生成できない
end note


note left of 予約終了日時
10:15-19:00
19:15,30,45はenumムリなので、ここで生成させない
end note

note right of 予約開始_時
enumを持つ動機として、
そもそも不正な値を選択させないこと
end note

@enduml